### PR TITLE
Add Complex Number Utility Functions and Resolve Merge Conflicts with PR #17

### PR DESCRIPTION
**Pull request by bored-arvi**
### Added Complex Number Utility Functions. Fixes Issue #2

This PR includes the following functions for complex number operations:

- **Normalize Complex Number**: Normalizes a complex number to unit magnitude.
- **Conjugate Complex Number**: Computes the conjugate of a complex number.
- **Reciprocal of a Complex Number**: Computes the reciprocal of a complex number.
- **Magnitude of a Complex Number**: Calculates the magnitude (absolute value) of a complex number.
- **Phase of a Complex Number**: Computes the phase (angle) of a complex number.
- **Nth Roots of a Complex Number**: Finds the Nth roots of a complex number.
- **Rotate a Complex Number**: Rotates a complex number by a given angle.

Descriptions of these functions have been added to the **README**, and corresponding unit tests have been included to ensure functionality.

### Merge Conflict Note

To avoid merge conflicts with PR #17, which also modifies the `maths.md` file, the changes from that PR have been included in this one as well.

### Request

Kindly review both sets of changes and tag them for the relevant issues, as they seem valid for inclusion. @J-B-Mugundh

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@bored-arvi kindly add implementation proof screenshot or video to state that the codes are working fine. 2-3 is enough in case of screenshot and 30 sec max if video.

**Comment by J-B-Mugundh** [comment]
@bored-arvi still having merge conflicts.. can u resolve them?

**Comment by bored-arvi** [comment]
Solved the merge conflict that arose due to changes made in maths.md by PR #17. Also included implementation video of three types of inputs: Purely Real, Purely Imaginary and a Real and Imaginary Input to cover all cases. @J-B-Mugundh 
https://github.com/user-attachments/assets/09dae995-33be-46a3-a7a6-05d75d27d0d4

**Comment by J-B-Mugundh** [comment]
@bored-arvi Good work!

**Comment by J-B-Mugundh** [comment]
@bored-arvi Kindly update the description by adding which issue this PR refers to, so it's easy for us to close the issue. 

Example: 

Fixes #<issue_number> or Closes #<issue_number> (This tells us that which issue this PR refers to)

**Pull request merged**
